import Head from "next/head";
import MeetLayout from "../../components/layout/MeetLayout";
import Link from "next/link";
import BDecoration from "../../components/utils/BDecoration";

const LivePage = () => {

    return (
        <div className="w-full h-screen ">
            <Head>
                <title>Discourses by AGORA SQUARE</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/discourse_logo_fav.svg" />
            </Head>

            <MeetLayout>
                {/* <div className='w-32 h-32 bg-gradient rounded-full blur-3xl fixed top-24 right-72 z-0 t-all' /> */}
                <BDecoration />
                <div className=' xl:aspect-video lg:max-h-[70vh] justify-center overflow-hidden w-full max-w-6xl flex gap-4 z-10 t-all'>
                    {/* TopSection */}

                    {/* <div className="w-full flex items-center justify-center">
                        <Branding />
                    </div> */}

                    {/* Body */}
                    {<div className="flex flex-col gap-2 mx-20 self-center items-center">
                        <h3 className="text-white/70  text-center font-Lexend text-xl font-semibold">Error!</h3>
                        {<p className="text-[#c6c6c6] text-center font-Lexend text-xs">Coul<span className="font-Lexend text-xs">d</span>n&apos;t find what you&apos;re looking for.</p>}
                        <Link href="/">
                            <a className="text-gradient text-sm font-Lexend">&larr; go back</a>
                        </Link>
                    </div>}


                </div>

            </MeetLayout>

        </div>
    );
}



export default LivePage;