import Head from "next/head"
import Layout from "../components/layout/Layout"
import TopBar from "../components/topbar/TopBar"

const containerCSS = "flex flex-col gap-2 mb-2"
const headingCSS = "text-white text-sm xs:text-base font-Lexend font-semibold"
const paraCSS = "text-[#E5F7FF] text-xs xs:text-sm font-medium leading-6" 

const Disclamer = () => {
    return (
        <div className="w-full h-screen overflow-x-clip">
            <Head>
                <title>Disclamer | AGORA SQUARE</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/discourse_logo_fav.svg" />
            </Head>
            <Layout>
                <TopBar onDiscoursePage={false} />
                <div className='w-full min-h-screen relative flex flex-col py-4 sm:py-5 mobile:pb-[80px] gap-3 sm:gap-4 z-10'>
                    <h1 className="font-Lexend font-bold text-lg text-white mb-4">DISCLAIMER</h1>

                    <div className={containerCSS}>
                        <h3 className={headingCSS}>WEBSITE DISCLAIMER</h3>
                        <p className={paraCSS}>{`The information provided by Agora Square ("we" "us"or "our") on http://www.agorasquare.xyz (the "Site") and our mobile application is for general informational purposes only All information on the Site and our mobile application is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site or our mobile application UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR OUR MOBILE APPLICATION OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE AND OUR MOBILE APPLICATION YOUR USE OF THE SITE AND OUR MOBILE APPLICATION AND YOUR RELIANCE ON ANY INFORMATION ON THE SITE AND OUR MOBILE APPLICATION IS SOLELY AT YOUR OWN RISK`}</p>
                    </div>

                    <div className={containerCSS}>
                        <h3 className={headingCSS}>EXTERNAL LINKS DISCLAIMER</h3>
                        <p className={paraCSS}>
                        The Site and our mobile application may contain (or you may be sent through the Site or our mobile application) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising Such external links are not investigated, monitored, or checked for accuracy, adequacy validity, reliability, Availability, or completeness by us. WE DO NOT WARRANT ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE OR ANY WEBSITE OR FEATURE LINKED IN ANY BANNER OR OTHER ADVERTISING WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD PARTY PROVIDERS OF PRODUCTS OR SERVICES
                        </p>
                    </div>

                    <div className={containerCSS}>
                        <h3 className={headingCSS}>PROFESSIONAL DISCLAIMER</h3>
                        <p className={paraCSS}>
                            The Site cannot and does not contain tech advice. The tech information is provided for gene informational and educational purposes only and is not a substitute for professional advice Accordingly before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of tech advice THE USE OR RELIANCE OF ANY INFORMATION CONTAINED ON THE SITE OR OUR MOBILE APPLICATION IS SOLELY AT YOUR OWN RISK
                        </p>
                    </div>

                    <div className={containerCSS}>
                        <h3 className={headingCSS}>AFFILIATES DISCLAIMER</h3>
                        <p className={paraCSS}>
                            The Site and our mobile application may continue links to affiliate websites, and we receive an affiliate commission for any purchases made by you on the affiliate website using such links. Our affiliates include the following TESTIMONIALS DISCLAIMER
                            
                            The Site may contain testimonials by users of our products and/or services. These testimonials reflect the real-life experiences and opinions of such users. However, the experiences are personal to those particular users and may not necessarily be representative of all users of our products and/or services We do not claim, and you should not assume that all users will have the same experience YOUR INDIVIDUAL RESULTS MAY VARY
                            
                            The testimonials on the Site are submitted in various forms such as text, audio and/or video, and are reviewed by us before being posted They appealon the Site verbatim as given by the users except for the correction of grammar or typing errors some testimonials may have been shortened for the sake of brevity where the full testimonial contained extraneous information not relevant to the general public.
                            
                            The views and opinions contained in the testimonials belong solely to the individual user and do not reflect our views and opinions We are not affiliated with users who provide testimonials, and users are not paid or otherwise compensated for the testimonials

                            The testimonials on the Site are not intended, nor should they be construed as claims that our products and/or services can be used to diagnose, treat, mitigate cure prevent, or otherwise be used for any disease or medical condition No testimonials have been clinically proven or evaluated
                        </p>
                    </div>
                </div>
            </Layout>
            </div>
    )
}

export default Disclamer