import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState, useContext, useEffect } from "react";
import Layout from "../../components/layout/Layout";
import TopBar from "../../components/topbar/TopBar";
import Tabs from "../../components/user/Tabs";
import AppContext from "../../components/utils/AppContext";
import BDecoration from "../../components/utils/BDecoration";
import LoadingSpinner from "../../components/utils/LoadingSpinner";
import {
    ArrowNE,
    TwitterIcon,
} from "../../components/utils/SvgHub";

const UserPage = () => {
    const route = useRouter();
    const [loading, setLoading] = useState(false);

    const { loggedIn, t_handle, t_name,t_connected, walletAddress } = useContext(AppContext);

    useEffect(() => {
        if(!loggedIn || !t_connected){
            route.push('/');
        }
    },[loggedIn,t_connected]);

    if(route.query.userId !== walletAddress){
        route.push('/');
    }

    return (
        <>
            {loggedIn && t_connected && (route.query.userId === walletAddress) && (
                <div className="w-full h-screen">
                    <Head>
                        <title>Discourses by AGORA SQUARE</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/discourse_logo_fav.svg" />
                    </Head>

                    <Layout>
                        <BDecoration />

                        <div className="w-full min-h-screen flex flex-col py-10 gap-4 z-10">
                            <TopBar showLogo={false} />

                            {loading ? (
                                <div className="flex-1 flex justify-center items-center">
                                    <LoadingSpinner strokeColor="#ffffff" />
                                </div>
                            ) : (
                                // Main Body
                                <div className="flex flex-col items-center gap-4">
                                    {/* Profile Pic Section */}
                                    <div className="w-[80px] h-[80px]">
                                        <img
                                            src="/user_photo.png"
                                            alt="Person profile pic"
                                            className="w-full h-full ios_curve"
                                        />
                                    </div>

                                    {/* About Section*/}
                                    <div className="flex flex-col items-center gap-4">
                                        <div className="flex flex-col gap-1">
                                            <h1 className="text-gradient text-2xl text-center font-semibold font-Lexend">
                                                {t_name}
                                            </h1>
                                            <div className="flex items-center">
                                                <a
                                                    href={`https://www.twitter.com/${t_handle}`}
                                                    target="_blank"
                                                    rel="noreferrer"
                                                >
                                                    <div className="flex items-center cursor-pointer">
                                                        <div className="mr-2">
                                                            <TwitterIcon
                                                                color="#C0C0C0"
                                                                width={16}
                                                                height={16}
                                                            />
                                                        </div>
                                                        <span className="text-[#D5D5D5] text-xs font-semibold hover:underline underline-offset-2">
                                                            @{t_handle}
                                                        </span>
                                                        <ArrowNE color="#C0C0C0" />
                                                    </div>
                                                </a>

                                                {/* Divider */}
                                                <div className="w-[2px] mx-2 h-4 bg-[#444444] flex rounded-xl" />
                                                <div className="flex items-center cursor-pointer">
                                                    <span className="text-[#D5D5D5] text-xs font-semibold hover:underline underline-offset-2">
                                                        0xb...8A3
                                                    </span>
                                                    <ArrowNE color="#C0C0C0" />
                                                </div>
                                            </div>
                                        </div>

                                        {/* Bio Section */}
                                        <p className="text-[#BABABA] font-Lexend text-sm text-center max-w-lg">
                                            Bio comes here - It is a long established fact that a
                                            reader will be distracted by the readable content of a
                                            page when looking at its layout.
                                        </p>
                                    </div>

                                    <div className="mt-4 flex">
                                        <Stats />
                                    </div>

                                    <div className="mt-4 flex w-full">
                                        <Tabs />
                                    </div>
                                </div>
                            )}
                        </div>
                    </Layout>
                </div>
            )}
        </>
    );
};

export default UserPage;

const Stats = () => {
    return (
        <div className="flex gap-2 bg-[#0B0B0B] border-2 border-white/5 rounded-lg p-4 items-center">
            <div className="flex flex-col items-center">
                <h3 className="text-white font-Lexend text-[18px]">23</h3>
                <small className="text-[#BABABA] font-Lexend text-[11px]">
                    Discourse Funded
                </small>
            </div>

            {/* Divider */}
            <div className="w-[2px] mx-2 h-[90%] bg-[#444444] flex rounded-xl" />

            <div className="flex flex-col items-center">
                <h3 className="text-white font-Lexend text-[18px]">26</h3>
                <small className="text-[#BABABA] font-Lexend text-[11px]">
                    Discourse Invitation
                </small>
            </div>
        </div>
    );
};
