import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useContext, useEffect } from "react";
import Layout from "../../components/layout/Layout";
import TopBar from "../../components/topbar/TopBar";
import EditProfile from "../../components/user/EditProfile";
import NFTS from "../../components/user/NFTs";
import RecentActivity from "../../components/user/RecentActivity";
import Tabs from "../../components/user/Tabs";
import AppContext from "../../components/utils/AppContext";
import LoadingSpinner from "../../components/utils/LoadingSpinner";
import {TwitterIcon2, WalletIcon,} from "../../components/utils/SvgHub";
import { getProfileImageUrl } from "../../helper/StringHelper";

const ClassString = "bg-black border-2 border-[#1E1E1E] rounded-2xl p-3 text-[#E5F7FF] text-[10px] sm:text-xs font-Lexend font-medium";
const SelectedClassString = "!bg-[#D2B4FC] text-[#000000]"
const StatNumberClassString = "text-white text-lg sm:text-xl font-Lexend font-semibold"
const StatTextClassString = "text-[#7D8B92] text-[10px] sm:text-xs font-Lexend font-semibold"

const UserPage = () => {
    const route = useRouter();
    const [loading, setLoading] = useState(false);
    const [currentTab,setCurrentTab] = useState(0)

    const { loggedIn, t_handle,t_img,t_name,t_connected, walletAddress,bio,name } = useContext(AppContext);

    useEffect(() => {
        if(!loggedIn || !t_connected){
            route.push('/');
        }
    },[loggedIn,t_connected]);

    if(route.query.userId !== walletAddress){
        route.push('/');
    }

    return (
        <>
            {loggedIn && t_connected && (route.query.userId === walletAddress) && (
                <div className="w-full h-screen">
                    <Head>
                        <title>Discourses by AGORA SQUARE</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/discourse_logo_fav.svg" />
                    </Head>

                    <Layout>
                        <TopBar onDiscoursePage={false} />
                        <div className="w-full min-h-screen flex flex-col py-4 sm:py-5 mobile:pb-[90px] gap-4 z-10">
                            {loading ? (
                                <div className="flex-1 flex justify-center items-center">
                                    <LoadingSpinner strokeColor="#ffffff" />
                                </div>
                            ) : (
                                // Main Body
                                <div className="flex flex-col gap-8 sm:gap-14 relative">
                                    {/* User info section */}
                                    <section className="flex flex-col items-center xs2:items-start xs2:flex-row gap-2 xs2:gap-5 sm:gap-8">
                                        <img src={getProfileImageUrl(t_img)} alt="Person profile pic" className="w-24 h-24 sm:w-36 sm:h-36 object-cover rounded-[32px]"/>

                                        {/* Bio Section */}
                                        <div className="w-full xs2:max-w-fit flex flex-col items-center xs2:items-start gap-2">
                                            <div className="flex items-center gap-2">
                                                <h1 className="text-2xl font-Lexend text-white font-semibold">{name ? name : t_name}</h1>
                                                <EditProfile />
                                            </div>
                                            
                                            <div className="flex items-center gap-2">
                                                {/* Twitter handle */}
                                                <a href={`https://www.twitter.com/${t_handle}`} target="_blank" rel="noreferrer" className="flex items-center gap-1">
                                                    <TwitterIcon2 size={26}/>
                                                    <span className="text-[#498CD6] font-medium font-Lexend text-xs">@{t_handle}</span>
                                                </a>

                                                {/* Divider */}
                                                <div className="w-[1.2px] h-4 bg-white/20" />

                                                {/* Wallet Address */}
                                                <div className="flex items-center gap-1">
                                                    <WalletIcon size={23} />
                                                    <span className="text-[#E5F7FF] font-medium font-Lexend text-xs">0xb...8A3</span>
                                                </div>
                                            </div>

                                            {bio && <p className="text-[#E5F7FFE5] font-semibold text-[11px] sm:text-[13px]">{bio}</p>}

                                            {/* Divider */}
                                            <div className="w-full h-[1.2px] bg-[#1E1E1E]" />

                                            {/* Stats */}
                                            <div className="flex items-center gap-6">
                                                {/* Discourse funded */}
                                                <div className="flex flex-col items-center">
                                                    <big className={StatNumberClassString}>23</big>
                                                    <small className={StatTextClassString}>discourse funded</small>
                                                </div>

                                                {/* No of nfts */}
                                                <div className="flex flex-col items-center">
                                                    <big className={StatNumberClassString}>04</big>
                                                    <small className={StatTextClassString}>nfts</small>
                                                </div>

                                                {/* discourse invitation */}
                                                <div className="flex flex-col items-center">
                                                    <big className={StatNumberClassString}>26</big>
                                                    <small className={StatTextClassString}>discourse invitation</small>
                                                </div>
                                            </div>
                                        </div>
                                    </section>

                                    {/* NFTs & Recent Activity Section */}
                                    <section className="flex flex-col gap-4">
                                        <div className="flex items-center gap-3">
                                            <button onClick={() => setCurrentTab(0)} className={ClassString+" "+(currentTab == 0 && SelectedClassString)}>NFTs</button>
                                            <button onClick={() => setCurrentTab(1)} className={ClassString+" "+(currentTab == 1 && SelectedClassString)}>Recent Activities</button>
                                        </div>

                                        <div>
                                            {currentTab === 0 ? <NFTS /> : <RecentActivity />}
                                        </div>
                                    </section>
                                </div>       
                            )}
                        </div>
                    </Layout>
                </div>
            )}
        </>
    );
};

export default UserPage;