apiVersion: v1
kind: Service
metadata:
  name: {{ include "agora-discourses-chart.fullname" . }}
  labels:
    {{- include "agora-discourses-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000  # Specify the target port as 3000
      protocol: TCP
      name: http
  selector:
    {{- include "agora-discourses-chart.selectorLabels" . | nindent 4 }}
